name: Deploy Vue + Vuetify to Pages

on:
  push:
    branches: 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4 # Actualizado a v4 para evitar problemas de compatibilidad
        with:
          version: 9 # O la versión específica de pnpm que uses localmente

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Cambiado a Node 22 para solucionar el warning de la imagen
          cache: 'pnpm'

      - name: Install dependencies
        # Agregamos --no-frozen-lockfile solo por si acaso hay discrepancias en el entorno de CI
        run: pnpm install --no-frozen-lockfile 

      - name: Build Project
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4